### ISSUE TITLE
Issue during adding of the WFX plugin

### ISSUE THREAD

**Issue by MrVitaly** [maximiliysiss/tc_docker#4]
Issue during adding of the WFX plugin (5th step in the [installation instruction](https://github.com/maximiliysiss/tc_docker?tab=readme-ov-file#instruction)).
TC version 9.22a

```
FileNotFoundException: Could not load file or assembly 'file:///<<path>>\TotalCommander.DockerPlugin.dll' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.ReflectionOnlyLoadFrom(String assemblyFile)
   at OY.TotalCommander.TcPluginTools.TcPluginLoader.AssemblyReflectionOnlyLoadFrom(String assemblyPath)
   at OY.TotalCommander.TcPluginTools.TcPluginLoader.GetPluginClass(String assemblyPath, PluginType pluginType, String pluginClassName)
   at OY.TotalCommander.TcPluginTools.TcPluginLoader.GetPluginClassNameCallback()
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at OY.TotalCommander.TcPluginTools.TcPluginLoader.GetPluginClassName(String pluginDll, PluginType pluginType, String pluginClassName)
   at OY.TotalCommander.TcPluginTools.TcPluginLoader.CreateTcPluginStub(AppDomain domain, String pluginAssembly, PluginType pluginType, String masterClassName, String& pluginClassName)
   at OY.TotalCommander.TcPluginTools.TcPluginLoader.GetTcPlugin(String wrapperAssembly, PluginType pluginType)
   at OY.TotalCommander.WfxWrapper.FsWrapper.get_Plugin()
   at OY.TotalCommander.WfxWrapper.FsWrapper.GetDefRootName(IntPtr rootName, Int32 maxLen)
```

**Comment by maximiliysiss** [comment]
Hello! 
Yes, I see that there is a failure
I hope that I will get a free time in this month to rewrite core of lib

**Comment by maximiliysiss** [comment]
@MrVitaly, hello!
v0.0.2 was released, so you can use it 

https://github.com/maximiliysiss/tc_docker/releases/tag/0.0.2

**Comment by MrVitaly** [comment]
It works! Thank you, @maximiliysiss, so much! 🤝
